// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvKlvYVg5RftBb4us1FjmtDIYzRgZkDus',
    appId: '1:416476394675:web:c66abeb4b5b68bb4a36cc6',
    messagingSenderId: '416476394675',
    projectId: 'hksn-staff',
    authDomain: 'hksn-staff.firebaseapp.com',
    storageBucket: 'hksn-staff.appspot.com',
    measurementId: 'G-2JQM5885YS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA34Fc4a1eCEVyIjPCfwiGnbhgmOy-ZWuU',
    appId: '1:416476394675:android:316c0817a6ba105ea36cc6',
    messagingSenderId: '416476394675',
    projectId: 'hksn-staff',
    storageBucket: 'hksn-staff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuUDOZrcfpl8xS-WlvW6pBaA3cqhuouyM',
    appId: '1:416476394675:ios:1bf8286c8a97a96ba36cc6',
    messagingSenderId: '416476394675',
    projectId: 'hksn-staff',
    storageBucket: 'hksn-staff.appspot.com',
    iosClientId: '416476394675-vuglekcnvn1bn4ttbajkg4chujhanm3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.nellikka',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuUDOZrcfpl8xS-WlvW6pBaA3cqhuouyM',
    appId: '1:416476394675:ios:1bf8286c8a97a96ba36cc6',
    messagingSenderId: '416476394675',
    projectId: 'hksn-staff',
    storageBucket: 'hksn-staff.appspot.com',
    iosClientId: '416476394675-vuglekcnvn1bn4ttbajkg4chujhanm3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.nellikka',
  );
}
